baseURL = "https://citation.jltml.me/"
languageCode = "en-us"
title = "The Citation"
theme = "hugo-PaperMod"
[minify]
  minifyOutput = true
[taxonomies]
  sections = "sections"
  issue = "issues"
[permalinks]
  articles = "/articles/:title/"
[params]
  defaultTheme = 'auto'
  disableThemeToggle = true
  disableSpecial1stPost = true
  ShowReadingTime = false
  comments = false
  [params.homeInfoParams]
    title = "*The Citation*"
    content = "STA's school newspaper, est. 2020."
  [[menu.main]]
    identifier = "sections"
    name = "sections"
    url = "/sections/"
    weight = 10
  [[menu.main]]
    identifier = "issues"
    name = "issues"
    url = "/issues/"
    weight = 20
  [[menu.main]]
    identifier = "archive"
    name = "archive"
    url = "/archives/"
    weight = 30
  [[menu.main]]
    identifier = "search"
    name = "search"
    url = "/search/"
    weight = 40
[outputs]
  home = [ "HTML", "RSS", "JSON" ]
