baseURL = "https://citation.jltml.me/"
languageCode = "en-us"
title = "The Citation"
theme = "hugo-PaperMod"
[minify]
  minifyOutput = true
[taxonomies]
  section = "sections"
[params]
  defaultTheme = 'auto'
  disableThemeToggle = true
  disableSpecial1stPost = true
  ShowReadingTime = true
  [[menu.main]]
    identifier = "sections"
    name = "sections"
    url = "/sections/"
    weight = 10
  [[menu.main]]
    identifier = "archive"
    name = "archive"
    url = "/archives/"
    weight = 30
  [[menu.main]]
    identifier = "search"
    name = "search"
    url = "/search/"
    weight = 40
[outputs]
  home = [ "HTML", "RSS", "JSON" ]
